---

- name: Install UFW
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Disable UFW
  ufw:
    state: disabled

- name: Disable swap
  shell:
    cmd: |
      swapoff -a
  args:
    executable: /bin/bash

- name: Remove Swap from fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Let iptables see bridged traffic and disable IPv6
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
  loop:
    - net.ipv4.ip_forward
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: Add the overlay and br_netfilter modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - "overlay"
    - "br_netfilter"

- name: Make the kernel modules persistent
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/kubernetes.conf
    mode: '0644'

- name: Ensure containerd is installed.
  apt:
    name: containerd
    state: present

- name: Ensure containerd is started and enabled at boot.
  service:
    name: containerd
    state: started
    enabled: true

- name: Ensure containerd config directory exists.
  file:
    path: /etc/containerd
    state: directory
  register: containerd_dir

- name: Generate default containerd config
  shell: containerd config default
  register: containerd_default_config

- name: Generate containerd config with SystemdCgroup enabled
  copy:
    content: "{{ containerd_default_config.stdout | regex_replace('SystemdCgroup = false', 'SystemdCgroup = true') }}"
    dest: /etc/containerd/config.toml
    backup: yes
  when: containerd_dir.changed

- name: Restart containerd
  service:
    name: containerd
    state: restarted
  when: containerd_dir.changed

- name: Install kubeadm dependancies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg

- name: Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes repo GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: '0644'

- name: Dearmor and install Kubernetes GPG key
  command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add needed repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    filename: kubernetes
    state: present
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Check if helm is installed
  ansible.builtin.command: helm version --short
  register: helm_check
  changed_when: false
  failed_when: false

- name: Install helm
  ansible.builtin.shell: curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: helm_check.rc != 0

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Ensure kubelet is started and enabled at boot.
  service:
    name: kubelet
    state: started
    enabled: true